services:
  - type: web
    name: uni.ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: API_KEY
        value: modalresearch_YVjsyMB3XwZEe9nQnaSDmQgELhoUq8_66FAJBo16VQY
